#spring:
#  data:
#    mongodb:
#      authentication-database: admin
#      username: testUser
#      password: 123456
#      database: test
#      port: 27017
#      host: localhost
#server:
#  port: 8585
#springdoc:
#  api-docs:
#    path: /api-docs
#logging:
#  level:
#    org:
#      springframework:
#        data: debug